### ISSUE TITLE
APNIC_ECON service is down, any "mirrors" available?

### ISSUE THREAD

**Issue by ghost** [emileaben/eyeballtrace#2]
I found that service is down (or not available for me).
python eyeballtrace -c DE 58.20.xxx.xxx
data URL unavailable, exiting (URL:http://data.labs.apnic.net/ipv6-measurement/Economies/CN/CN.asns.json?m=1)
Traceback (most recent call last):
  File "eyeballtrace", line 165, in <module>
    doit( args )
  File "eyeballtrace", line 80, in doit
    probe_selection,econdata,prb2as = select_probes_based_on_market( args )
  File "eyeballtrace", line 60, in select_probes_based_on_market
    if len( econdata ) == 0:
UnboundLocalError: local variable 'econdata' referenced before assignment

In eyeballtrace code I found it's pointing to
APNIC_ECON_URL="http://data.labs.apnic.net/ipv6-measurement/Economies/%s/%s.asns.json?m=1"

1) Any mirrors available for this service?
2) Maybe it's good idea to handle that exception and return much user friendly error message.

**Comment by emileaben** [comment]
1) no, but could think of having a cache in the program itself (once info
for a country is known, cache that for X days/weeks)
2) good idea (wrap exception / user friendly message)

pull requests appreciated
